modLoader="javafml"
loaderVersion="${loader_version_range}"

mixinConfigs = "window_box.mixins.json"

license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile="logo.png"

[[dependencies."${mod_id}"]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="botania"
    mandatory=true
    versionRange="${botania_version_range}"
    ordering="NONE"
    side="BOTH"

## Optional
[[dependencies."${mod_id}"]]
    modId="jei"
    mandatory=false
    versionRange="${jei_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="gravityapi"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"